### ISSUE TITLE
com.linkgap.cloud.config.secirity.component.AccessDecisionProcessor#vote

### ISSUE THREAD

**Issue by AwadYoo** [rookie-ricardo/spring-boot-learning-demo#1]
` // 如果缓存中没有此权限也就是未保护此API，弃权
        MenuPermission permission = caffeineCache.get(CacheName.PERMISSION, key, MenuPermission.class);
        if (permission == null) {
            return ACCESS_ABSTAIN;
        }
`
这里弃权的话，不是等于放行嘛

**Comment by he-erduo** [comment]
弃权不等于放行，因为是好几个投票器在工作，可以再看看我写的相关文章。

**Comment by he-erduo** [comment]
> `// 如果缓存中没有此权限也就是未保护此API，弃权 MenuPermission permission = caffeineCache.get(CacheName.PERMISSION, key, MenuPermission.class); if (permission == null) { return ACCESS_ABSTAIN; }`
> 这里弃权的话，不是等于放行嘛

弃权不等于放行，因为是好几个投票器在工作，可以再看看我写的相关文章。

**Comment by AwadYoo** [comment]
在demo里
```
    @Bean
    public AccessDecisionManager accessDecisionManager() {
        // 构造一个新的AccessDecisionManager 放入两个投票器
        List<AccessDecisionVoter<?>> decisionVoters = Arrays.asList(new WebExpressionVoter(), accessDecisionProcessor());
        return new UnanimousBased(decisionVoters);
    }
```
WebExpressionVoter 的作用什么呢

**Comment by AwadYoo** [comment]
现在的问题是这样，我们的权限认证应当遵循最小原则，但是 WebExpressionVoter 会在无权限配置的情况下投同意票，造成有权限访问

**Comment by he-erduo** [comment]
> 在demo里
> 
> ```
>     @Bean
>     public AccessDecisionManager accessDecisionManager() {
>         // 构造一个新的AccessDecisionManager 放入两个投票器
>         List<AccessDecisionVoter<?>> decisionVoters = Arrays.asList(new WebExpressionVoter(), accessDecisionProcessor());
>         return new UnanimousBased(decisionVoters);
>     }
> ```
> 
> WebExpressionVoter 的作用什么呢

具体可以参见我写的这篇文章，里面有说明：https://juejin.cn/post/6847902222668431368

**Comment by he-erduo** [comment]
> WebExpressionVoter

WebExpressionVoter 是为了对在SpringSecurityConfig文件中配置的URL进行投票，所以它并不是都投同意票，而是针对你的配置进行投票，对没有手动配置的URL（这里不手动配置是因为可能有上百个URL，数量太多不好配置）而使用accessDecisionProcessor投票器进行处理，具体可以参见我上面评论中的文章。
